postsubmits:
  ppc64le-cloud/builds:
    - name: postsubmit-master-golang-etcd-build-test-ppc64le
      cluster: k8s-ppc64le-cluster
      decorate: true
      branches:
        - master
      run_if_changed: '^golang/master/'
      extra_refs:
        - base_ref: main
          org: etcd-io
          repo: etcd
          workdir: true
      spec:
        containers:
          - image: quay.io/powercloud/all-in-one:0.6
            resources:
            requests:
              cpu: "5000m"
            limits:
              cpu: "5000m"
            command:
              - /bin/bash
            args:
              - -c
              - |
                set -o errexit
                set -o nounset
                set -o pipefail
                set -o xtrace

                build_commit=$(jq -r .commit $GOPATH/src/github.com/ppc64le-cloud/builds/golang/master/build.yaml)
                build_project=$(jq -r .project $GOPATH/src/github.com/ppc64le-cloud/builds/golang/master/build.yaml)
                curl -X GET http://build-bot.prow:8090/build\?project\=$build_project\&commit\=$build_commit -o /tmp/golang.tar.gz
                rm -rf /usr/local/go
                tar -C /usr/local -xzf /tmp/golang.tar.gz
                export PATH=/usr/local/go/bin:$PATH
                export PATH=$GOPATH/bin:$PATH
                export KEEP_GOING_MODULE=true
                export KEEP_GOING_SUITE=true
                go version
                ./scripts/build.sh
                GOARCH=`go env GOARCH` GO_TEST_FLAGS="-skip=TestWatchDelay" make test
